SELECT 
    NAME,
    PUNISHMENT
FROM (    
    SELECT
        CRIME_ID,
        PUNISHMENT
            FROM PUNISHMENT INNER JOIN CRIME
        ON CRIME.CRIME_ID = PUNISHMENT.PUNISHMENT_ID
        GROUP BY PUNISHMENT
        HAVING DESCRIPTION = 'Theft'
    ) 
INNER JOIN(
    SELECT 
        NAME,
        CRIME
    FROM FREEDINMATES 
        
    UNION

    SELECT 
        NAME,
        CRIME
    FROM RUMTHEFT) AS FREEDINMATES
ON FREEDINMATES.CRIME = CRIME_ID