SELECT '1 : ' || CAST(printf("%.2f", AVG(CAST (OUTPUT AS REAL) / CAST (INPUT AS REAL)))AS TEXT) AS FACTORY_CONVERSION
  FROM WORKPLACE
       LEFT JOIN
       WORKPLACE_DESCRIPTION ON WORKPLACE = ID
 WHERE WORKPLACE BETWEEN 2 AND 6;
 