SELECT DESCRIPTION,
       CAST(printf("%.1f", CAST (OUTPUT AS REAL) / CAST (INPUT AS REAL))*100 AS TEXT) || ' %' AS CONVERSION_RATIO
  FROM WORKPLACE
       LEFT JOIN
       WORKPLACE_DESCRIPTION ON WORKPLACE = ID
 WHERE WORKPLACE BETWEEN 2 AND 6
 GROUP BY WORKPLACE;
