SELECT
      BELONGSTO
    , KINDOFRUM
    , SUM(VALUE) AS SELLPRICE
    , HIDINGTAXES
    , ROUND(SUM(VALUE*(HIDINGTAXES/100)),2) AS CUTOFF
    , COUNT(*) AS BARRELS
FROM RUMHIDEOUT 
GROUP BY BELONGSTO, KINDOFRUM
HAVING SELLPRICE > 650